### PR TITLE
Draft of Steve's EDA proposal

### PR DESCRIPTION
**Pull request by steveazzolin**
This is the first draft of my EDA (not complete). Because I adopted a quite didactic approach (maybe useful for beginners) I would like a feedback if continuing in this way or not.
Basically I tried to present not only the "final result", but the idea is to construct step by step the EDA, for example showing also common errors that can be made (like poor interpretability with the first Pie Chart). 

I added also a very general consideration like the small intro just to do not start immediatly with coding.

### CODE REVIEW

**Comment by Erlemar** [comment]
Thank you for this contribution!
I like your style of explaining things and analysis.
Plotly express is a cool way to make nice visualizations easily. And I like the style of your plots
As far as I see, you use some plugin/extension to make pandas output prettier. Could you share it?

I have several suggestions about changes in the code, which could make things easier for beginners to understand what is going on:

In [4]:
I suggest one of the following two ways of renaming columns:
* `df = df.rename(columns={'col1_old_name': 'col2_old_name})`
* `df.columns = [list of columns]`

In [7]
Maybe replace `df.groupby("Country").size()` with `df["Country"].value_counts()`?

In [11]
Maybe replace
```
countries_to_plot = countries.sort_values(by="Count", ascending=False)[:K] #select K countries with more responses
countries_to_plot_reversed = countries_to_plot[::-1] #to plot Russia as the first element in the top of the plot
```

with `countries_to_plot_reversed = countries.sort_values(by="Count", ascending=True)[-K:]` ?

In [14]
I think it would be easier to understand if it was written like this:
```
top_K_countries = countries_to_plot["Country"][:K]
df_top_countries = df.loc[df['Country'].isin(top_K_countries)]
```

**Comment by steveazzolin** [comment]
Thank you for your tips, very useful.

In [11] actually doesn't work your tip, because It would return the elements from -K to 0, thus the last items. Anyway I updated to:
`countries_to_plot = countries.sort_values(by="Count", ascending=False)[K::-1]`

For this:

> As far as I see, you use some plugin/extension to make pandas output prettier. Could you share it?

Actually I am not using any extension/plugin. I simply write as last statement of the cell what I want to see without the `print()`

**Comment by steveazzolin** [comment]
I added a new section.

I think that can be very interesting in particular because It confirms the results of previous sections as you can read at the bottom of the notebook. The only problem is that I know the code isn't very easy.
What do you think ?

Moreover Do you know if It's possible to make anchors working on Github ? I had to remove and add simply a bolded reference to the number of the section

**Comment by Erlemar** [comment]
Thank you! I really like this approach. Showing top topics per country is quite interesting.

Here is an idea how to make the code more concise:

```
def my_func(df):
    most_common = Counter(df.sum().split()).most_common(3)
    labels = [e[0] for e in most_common]
    values = [e[1] for e in most_common]
    
    return labels, values

grouped = df_top_countries.groupby("Country")['Interests'].apply(my_func)

r , c = 1 , 1 #stands for row and column
for country, (labels, values) in zip(grouped.index, grouped.values):
    print(country, labels, values)
    fig.add_trace(go.Pie(labels=labels, values=values),r,c) #Define pie chart subplot
    c = c + 1 #to place correcly each subplot into the 2x2 grid
    if c % 3 == 0:
        r = r + 1
        c = 1
```

Basically we do a group by with a custom function. Feel free to change it, if you wish.

As for anchors, sadly they don't work on Github. They work only if the notebook is viewed using nbviewer.

**Comment by Hiyorimi** [comment]
I think that we are ready to merge, but I guess that we should leave only one notebook in the repo. Can you also merge the notebooks together?

**Comment by steveazzolin** [comment]
> I think that we are ready to merge, but I guess that we should leave only one notebook in the repo. Can you also merge the notebooks together?

Do you mean to merge my notebook with the other one? How should I merge them ? Simply appending mine at the end or something more elaborate?

**Comment by Hiyorimi** [comment]
Yup, by manually moving code. I'm not aware of more sophisticated approach and would love to learn more, if you know any.

**Comment by steveazzolin** [comment]
> Yup, by manually moving code. I'm not aware of more sophisticated approach and would love to learn more, if you know any.

Yeah sorry, I used the wrong word. I was meaning to simply concat the notebooks or If I had to integrate also from a semantic point of view the notebooks (adding explanation of the other notebook ecc...)
Anyway I concatenated notebooks together and pushed.

@Erlemar thank you for your tips, very useful also to better understand Python's features (I'm quite new to Python)

**Comment by Hiyorimi** [comment]
Congrats!

**Pull request merged**
